# Generated by Django 5.2.1 on 2025-06-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemographicsDimension',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('university', models.CharField(max_length=100)),
                ('degree_level', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MentalHealthAssessmentFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('mental_health_id', models.IntegerField()),
                ('study_satisfaction', models.IntegerField()),
                ('academic_workload', models.IntegerField()),
                ('academic_pressure', models.IntegerField()),
                ('financial_concerns', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MentalHealthDimension',
            fields=[
                ('mental_health_id', models.IntegerField(primary_key=True, serialize=False)),
                ('depression_level', models.IntegerField()),
                ('anxiety_level', models.IntegerField()),
                ('isolation_level', models.IntegerField()),
                ('social_relationships_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NegativeEngagementDimension',
            fields=[
                ('negative_engagement_id', models.IntegerField(primary_key=True, serialize=False)),
                ('academic_pressure', models.IntegerField()),
                ('academic_workload', models.IntegerField()),
                ('financial_concerns', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PositiveEngagementDimension',
            fields=[
                ('positive_engagement_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sports_engagement', models.TextField()),
                ('study_satisfaction', models.IntegerField()),
            ],
        ),
    ]
